//-----  arcticmodal  -----//
(function(d){var g={type:"html",content:"",url:"",ajax:{},ajax_request:null,ajax_preload:!0,closeOnEsc:!0,closeOnOverlayClick:!0,clone:!1,overlay:{block:!1,tpl:'<div class="arcticmodal-overlay"></div>',css:{backgroundColor:"#241c0f",opacity:.8}},container:{block:!1,tpl:'<div class="arcticmodal-container"><table class="arcticmodal-container_i"><tr><td class="arcticmodal-container_i2"></td></tr></table></div>'},wrap:void 0,body:void 0,errors:{tpl:'<div class="arcticmodal-error arcticmodal-close"></div>',
autoclose_delay:2E3,ajax_unsuccessful_load:"Error"},openEffect:{type:"fade",speed:400},closeEffect:{type:"fade",speed:400},beforeOpenModal:d.noop,afterOpenModal:d.noop,beforeCloseModal:d.noop,afterCloseModal:d.noop,afterLoadingModal:d.noop,afterLoadingModalOnShow:d.noop,errorLoadingModal:d.noop},m=0,f=d([]),n={isEventOut:function(a,b){var c=!0;d(a).each(function(){d(b.target).get(0)==d(this).get(0)&&(c=!1);0==d(b.target).closest("HTML",d(this).get(0)).length&&(c=!1)});return c}},e={getParentEl:function(a){var b=
d(a);return b.data("arcticmodal")?b:(b=d(a).closest(".arcticmodal-container").data("arcticmodalParentEl"))?b:!1},transition:function(a,b,c,e){e=void 0==e?d.noop:e;switch(c.type){case "fade":"show"==b?a.fadeIn(c.speed,e):a.fadeOut(c.speed,e);break;case "none":"show"==b?a.show():a.hide(),e()}},prepare_body:function(a,b){d(".arcticmodal-close",a.body).unbind("click.arcticmodal").bind("click.arcticmodal",function(){b.arcticmodal("close");return!1})},init_el:function(a,b){var c=a.data("arcticmodal");if(!c){c=
b;m++;c.modalID=m;c.overlay.block=d(c.overlay.tpl);c.overlay.block.css(c.overlay.css);c.container.block=d(c.container.tpl);c.body=d(".arcticmodal-container_i2",c.container.block);b.clone?c.body.html(a.clone(!0)):(a.before('<div id="arcticmodalReserve'+c.modalID+'" style="display: none" />'),c.body.html(a));e.prepare_body(c,a);c.closeOnOverlayClick&&c.overlay.block.add(c.container.block).click(function(b){n.isEventOut(d(">*",c.body),b)&&a.arcticmodal("close")});c.container.block.data("arcticmodalParentEl",
a);a.data("arcticmodal",c);f=d.merge(f,a);d.proxy(l.show,a)();if("html"==c.type)return a;if(void 0!=c.ajax.beforeSend){var h=c.ajax.beforeSend;delete c.ajax.beforeSend}if(void 0!=c.ajax.success){var k=c.ajax.success;delete c.ajax.success}if(void 0!=c.ajax.error){var g=c.ajax.error;delete c.ajax.error}var p=d.extend(!0,{url:c.url,cache:!0,beforeSend:function(){void 0==h?c.body.html('<div class="arcticmodal-loading" />'):h(c,a)},success:function(b){if(!0===c.ajax_preload){a.trigger("afterLoadingModal");
c.afterLoadingModal(c,a,b);var d=$(b),f=d.find("img").add(d.filter("img")),g=0,h=$.Deferred();f.each(function(){this.complete||4===this.readystate?(g++,g===f.length&&h.resolve()):$(this).load(function(){g++;g===f.length&&h.resolve()})});h.done(function(){void 0==k?c.body.html(b):k(c,a,b);e.prepare_body(c,a);setTimeout(function(){a.trigger("afterLoadingModalOnShow");c.afterLoadingModalOnShow(c,a,b)},100)})}else a.trigger("afterLoadingModal"),c.afterLoadingModal(c,a,b),void 0==k?c.body.html(b):k(c,
a,b),e.prepare_body(c,a),setTimeout(function(){a.trigger("afterLoadingModalOnShow");c.afterLoadingModalOnShow(c,a,b)},100)},error:function(){a.trigger("errorLoadingModal");c.errorLoadingModal(c,a);void 0==g?(c.body.html(c.errors.tpl),d(".arcticmodal-error",c.body).html(c.errors.ajax_unsuccessful_load),d(".arcticmodal-close",c.body).click(function(){a.arcticmodal("close");return!1}),c.errors.autoclose_delay&&setTimeout(function(){a.arcticmodal("close")},c.errors.autoclose_delay)):g(c,a)}},c.ajax);
c.ajax_request=d.ajax(p);a.data("arcticmodal",c)}},init:function(a){a=d.extend(!0,{},g,a);if(d.isFunction(this))if(void 0==a)d.error("jquery.arcticmodal: Uncorrect parameters");else if(""==a.type)d.error('jquery.arcticmodal: Don\'t set parameter "type"');else switch(a.type){case "html":if(""==a.content){d.error('jquery.arcticmodal: Don\'t set parameter "content"');break}var b=a.content;a.content="";return e.init_el(d(b),a);case "ajax":if(""==a.url)d.error('jquery.arcticmodal: Don\'t set parameter "url"');
else return e.init_el(d("<div />"),a)}else return this.each(function(){e.init_el(d(this),d.extend(!0,{},a))})}},l={show:function(){var a=e.getParentEl(this);if(!1===a)d.error("jquery.arcticmodal: Uncorrect call");else{var b=a.data("arcticmodal");b.overlay.block.hide();b.container.block.hide();d("BODY").append(b.overlay.block);d("BODY").append(b.container.block);b.beforeOpenModal(b,a);a.trigger("beforeOpenModal");if("hidden"!=b.wrap.css("overflow")){b.wrap.data("arcticmodalOverflow",b.wrap.css("overflow"));
var c=b.wrap.outerWidth(!0);b.wrap.css("overflow","auto");var g=b.wrap.outerWidth(!0);g!=c&&b.wrap.css("marginRight",g-c+"px")}f.not(a).each(function(){d(this).data("arcticmodal").overlay.block.hide()});e.transition(b.overlay.block,"show",1<f.length?{type:"none"}:b.openEffect);e.transition(b.container.block,"show",1<f.length?{type:"none"}:b.openEffect,function(){b.afterOpenModal(b,a);a.trigger("afterOpenModal")});return a}},close:function(){if(d.isFunction(this))f.each(function(){d(this).arcticmodal("close")});
else return this.each(function(){var a=e.getParentEl(this);if(!1===a)d.error("jquery.arcticmodal: Uncorrect call");else{var b=a.data("arcticmodal");!1!==b.beforeCloseModal(b,a)&&(a.trigger("beforeCloseModal"),f.not(a).last().each(function(){d(this).data("arcticmodal").overlay.block.show()}),e.transition(b.overlay.block,"hide",1<f.length?{type:"none"}:b.closeEffect),e.transition(b.container.block,"hide",1<f.length?{type:"none"}:b.closeEffect,function(){b.afterCloseModal(b,a);a.trigger("afterCloseModal");
b.clone||d("#arcticmodalReserve"+b.modalID).replaceWith(b.body.find(">*"));b.overlay.block.remove();b.container.block.remove();a.data("arcticmodal",null);d(".arcticmodal-container").length||(b.wrap.data("arcticmodalOverflow")&&b.wrap.css("overflow",b.wrap.data("arcticmodalOverflow")),b.wrap.css("marginRight",0))}),"ajax"==b.type&&b.ajax_request.abort(),f=f.not(a))}})},setDefault:function(a){d.extend(!0,g,a)}};d(function(){g.wrap=d(document.all&&!document.querySelector?"html":"body")});d(document).bind("keyup.arcticmodal",
function(a){var b=f.last();b.length&&b.data("arcticmodal").closeOnEsc&&27===a.keyCode&&b.arcticmodal("close")});d.arcticmodal=d.fn.arcticmodal=function(a){if(l[a])return l[a].apply(this,Array.prototype.slice.call(arguments,1));if("object"===typeof a||!a)return e.init.apply(this,arguments);d.error("jquery.arcticmodal: Method "+a+" does not exist")}})(jQuery);
$(document.body).on("click","[data-modal]",function(a){a.preventDefault(),a=$(this).attr("data-modal"),$("#"+a).arcticmodal()});
$(document.body).on("click",'a[href^="#modal-"]',function(c){c.preventDefault(),c=$(this).attr("href"),$(c).arcticmodal()});